clear:
	rm -f *.aux *.bbl *.dvi *.fdb_latexmk *.fls *.out assets/*.pdf *.synctex.gz *.lof *.log *.lot *.toc *_temp.tex *.blg

clean:
	rm -f *.aux *.bbl *.dvi *.fdb_latexmk *.fls *.out assets/*.pdf *.synctex.gz *.lof *.log *.lot *.toc *_temp.tex *.blg *.xml *.bcf
