package org.fosstrak.capturingapp
 
import org.fosstrak.capturingapp.util.Util; 
import org.fosstrak.ale.xsd.ale.epcglobal.ECReport;
import org.fosstrak.ale.xsd.ale.epcglobal.ECReports;
import org.fosstrak.ale.xsd.ale.epcglobal.ECReportGroupListMember;
import org.fosstrak.ale.xsd.epcglobal.EPC;
import org.fosstrak.capturingapp.util.SimpleEPCISDocument;
import org.fosstrak.epcis.model.ActionType;

import java.util.List;
import java.util.LinkedList;
import function org.fosstrak.capturingapp.util.Util.extractEPC;
import function org.fosstrak.capturingapp.util.Util.extractReportMembers;

// the global collector for all the EPCIS documents for further processing.
global java.util.List epcisResults

function List warehouseReportHandler(List reports, String reportName){
	// List of ECReports
	List epcs = new LinkedList();

	for(Object rs : reports){
		if(rs instanceof ECReports){
			ECReports rsc = (ECReports) rs;
			for(ECReport report : rsc.getReports().getReport()){
				if(report.getReportName() == reportName){
					ecps.addAll(extractEPC(Util.selectTag, report));
				}
			}
		}
	}

	return epcs;
}

rule "ADDITIONS Rule Tags from reader 'Reader_Warehouse_Shelve1' from the specName 'ECSpec'"
	dialect "java"
	when
		$reports : ECReports( reports != null)
		$epcs : LinkedList( size > 0 ) from collect (
			EPC() from warehouseReportHandler($reports, "additions")
			)  
	then
	
		SimpleEPCISDocument simpleDocument = new SimpleEPCISDocument();
		simpleDocument.addObjectEvent(
			$epcs, 
			ActionType.OBSERVE, 
			"urn:epcglobal:cbv:bizstep:storing", 
			"urn:epcglobal:cbv:disp:sellable_not_accessible",
			"urn:epc:id:sgln:76300544.00000.1",
			"urn:epc:id:sgln:76300544.00000.0"
			);
		
		System.out.println("\n=====================================================");
		System.out.println("Additions tags seen:");
		for (Object o : $epcs) System.out.println(((EPC)o).getValue());
		System.out.println("=====================================================\n");

		epcisResults.add(simpleDocument.getDocument());
end

/* rule "DELETIONS Rule Tags from reader 'Reader_Warehouse_Shelve1' from the specName 'ECSpec'"
	dialect "java"
	when
		reports : ECReports()
		$epcs : LinkedList( size > 0 ) from collect (
			EPC() from warehouseReportHandler(reports, "deletions")
			) 
	then
	
		SimpleEPCISDocument simpleDocument = new SimpleEPCISDocument();
		simpleDocument.addObjectEvent(
			$epcs, 
			ActionType.OBSERVE, 
			"urn:epcglobal:cbv:bizstep:unpacking",
			"urn:epcglobal:cbv:disp:partially_dispensed",
			"urn:epc:id:sgln:76300544.00000.1",
			"urn:epc:id:sgln:76300544.00000.0"
			);
		System.out.println("\n=====================================================");
		System.out.println("Deletions tags seen:");
		for (Object o : $epcs) System.out.println(((EPC)o).getValue());
		System.out.println("=====================================================\n");

		epcisResults.add(simpleDocument.getDocument());
end */